// Таблица экранов iPhone для apple-touch-startup-image (портрет) и цвета экрана запуска.
// Общая для генератора (`gen-startup-images.mjs`) и теста согласованности (`startup-images.test.mjs`).
// Ключ выбора картинки в Safari — точное совпадение device-width × device-height × pixel-ratio, поэтому
// размеры в pt и масштаб обязаны совпадать с реальными экранами; лишняя строка ничего не ломает.

/** Цвета — токены темы v2: светлая `--bg-grouped` (systemGroupedBackground), тёмная — чистый чёрный (OLED). */
export const LAUNCH_COLORS = {
  light: { hex: "#F2F2F7", rgb: [0xf2, 0xf2, 0xf7] },
  dark: { hex: "#000000", rgb: [0x00, 0x00, 0x00] },
};

/** @type {{ width: number, height: number, ratio: number, models: string }[]} — pt и масштаб */
export const DEVICES = [
  { width: 440, height: 956, ratio: 3, models: "iPhone 16 Pro Max" },
  { width: 402, height: 874, ratio: 3, models: "iPhone 16 Pro" },
  { width: 430, height: 932, ratio: 3, models: "iPhone 16 Plus, 15 Plus, 15 Pro Max, 14 Pro Max" },
  { width: 420, height: 912, ratio: 3, models: "iPhone Air" },
  { width: 393, height: 852, ratio: 3, models: "iPhone 16, 15, 15 Pro, 14 Pro" },
  { width: 428, height: 926, ratio: 3, models: "iPhone 14 Plus, 13 Pro Max, 12 Pro Max" },
  { width: 390, height: 844, ratio: 3, models: "iPhone 14, 13, 13 Pro, 12, 12 Pro" },
  { width: 375, height: 812, ratio: 3, models: "iPhone 13 mini, 12 mini, 11 Pro, XS, X" },
  { width: 414, height: 896, ratio: 3, models: "iPhone 11 Pro Max, XS Max" },
  { width: 414, height: 896, ratio: 2, models: "iPhone 11, XR" },
  { width: 414, height: 736, ratio: 3, models: "iPhone 8 Plus, 7 Plus, 6s Plus" },
  { width: 375, height: 667, ratio: 2, models: "iPhone SE 3, SE 2, 8, 7" },
  { width: 320, height: 568, ratio: 2, models: "iPhone SE 1, 5s" },
];

export const SCHEMES = /** @type {const} */ (["light", "dark"]);

export const pixelSize = (d) => ({ w: d.width * d.ratio, h: d.height * d.ratio });
export const fileName = (scheme, d) => {
  const { w, h } = pixelSize(d);
  return `launch-${scheme}-${w}x${h}.png`;
};
export const publicPath = (scheme, d) => `/splash/${fileName(scheme, d)}`;
export const mediaQuery = (scheme, d) =>
  `(device-width: ${d.width}px) and (device-height: ${d.height}px) and (-webkit-device-pixel-ratio: ${d.ratio}) and (orientation: portrait) and (prefers-color-scheme: ${scheme})`;

export const BLOCK_BEGIN = "<!-- startup-images:begin (generated by scripts/gen-startup-images.mjs) -->";
export const BLOCK_END = "<!-- startup-images:end -->";

/** Строки `<link>` для index.html. */
export function linkTags() {
  const lines = [];
  for (const d of DEVICES) {
    for (const scheme of SCHEMES) {
      lines.push(
        `    <link rel="apple-touch-startup-image" media="${mediaQuery(scheme, d)}" href="${publicPath(scheme, d)}" />`,
      );
    }
  }
  return lines.join("\n");
}
