/**
 * PD-155 — иконка приложения P4 «Девять клеток» (design/pd141-logo-round4.md): сборка ассетов из одной геометрии.
 *
 * Делает ровно два шага, оба воспроизводимы:
 *  1. пишет эталонные SVG в design/pd155-assets/ (light / dark / tinted, слой для Icon Composer, знак currentColor,
 *     favicon клеточный и сплошной) — геометрия записана здесь, руками SVG не правятся;
 *  2. растеризует PNG приложения в apps/web/public/icons/ (192, 512, apple-touch 180, favicon-32 клеточный,
 *     favicon-16 сплошной) и кладёт клеточный favicon как public/icons/icon.svg.
 *
 * Запускать РУКАМИ при смене иконки (в сборке не участвует: PNG лежат в git и смотрятся в ревью). Порты не занимает: file://.
 *
 *   cd <каталог с установленным playwright, напр. /tmp/pundoku-ios/pw> && node <repo>/design/pd155-icons.mjs
 *
 * Геометрия (канва 1024): столбцы 272/439/606, строки 189/356/523/690, клетка 146, зазор 21, радиус 30; раскладка
 * 3+2+3+1 = девять клеток; контрформа — клетка (плашка), чернил нет; запас до круга maskable 19.1.
 * Одна геометрия на все размеры иконки (P4 «читается везде», round 4 §4) — малой оптики, как у D5, нет.
 * 16-сеточные версии (favicon, Mark <= 60): клеточная — клетки 3×3 в (3,1)(7,1)(11,1)/(3,5)(11,5)/(3,9)(7,9)(11,9)/(3,13);
 * сплошная — контур «P» + контрформа 5×3; сплошная на 16 px, клеточная от 24 px.
 * Подачи (материалы те же, что у D5, round 4 §«Материалы иконки»): light — плашка #5A616E→#2B2F38→#14161B, клетки #E3E3E4;
 * dark — #3A404C→#1B1E25→#0A0B0E, клетки #B9BABB; tinted — #3A3A3C→#1C1C1E→#000000, клетки #9D9D9E (карта яркости для iOS).
 * Иконки обязаны быть непрозрачными (iOS кладёт веб-клип на чёрное); favicon-16/32 — с альфой, без плашки.
 */
import { createRequire } from "node:module";
const { chromium } = createRequire(process.cwd() + "/")("playwright");
import { copyFileSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const DIR = dirname(fileURLToPath(import.meta.url));
const ASSETS = join(DIR, "pd155-assets");
const OUT = join(DIR, "..", "apps", "web", "public", "icons");
mkdirSync(ASSETS, { recursive: true });
mkdirSync(OUT, { recursive: true });

const PATTERN = ["XXX", "X.X", "XXX", "X.."];
const cells = (x0, y0, step) => PATTERN.flatMap((row, r) => [...row].flatMap((ch, c) => (ch === "X" ? [{ x: x0 + c * step, y: y0 + r * step }] : [])));
const FULL = cells(272, 189, 167); // клетка 146 + зазор 21
const SMALL = cells(3, 1, 4); // клетка 3 + зазор 1
const fullRects = (fill) => FULL.map((c) => `<rect x="${c.x}" y="${c.y}" width="146" height="146" rx="30" fill="${fill}"/>`).join("\n    ");
const smallRects = () => SMALL.map((c) => `<rect x="${c.x}" y="${c.y}" width="3" height="3"/>`).join("\n    ");
const SOLID_D = "M3 1H14V10H6V15H3Z" + "M6 4V7H11V4Z";
const INK_FAVICON = "#5F6DF2"; // 4.24:1 на белой вкладке, 4.02:1 на тёмной (PD-98 §18.5з); не оборачивать в prefers-color-scheme

const APPEAR = {
  light: { stops: ["#5A616E", "#2B2F38", "#14161B"], mid: 0.45, paper: "#E3E3E4" },
  dark: { stops: ["#3A404C", "#1B1E25", "#0A0B0E"], mid: 0.45, paper: "#B9BABB" },
  tinted: { stops: ["#3A3A3C", "#1C1C1E", "#000000"], mid: 0.55, paper: "#9D9D9E" },
};

const iconSvg = (name, a) => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024" role="img" aria-label="Pundoku app icon, P4 Nine Cells, ${name} appearance">
  <title>Pundoku — P4 «Девять клеток» — ${name}</title>
  <desc>The letter P from nine cells on a 3x4 lattice (3+2+3+1): cell 146, gap 21, radius 30; the counter of the P is a cell-sized hole through to the ground, so the letter is carried by area, not colour. No ink, no filters, no baked effects. Fully opaque; the iOS mask is applied by the system. Generated by design/pd155-icons.mjs.</desc>
  <defs>
    <linearGradient id="p4-${name}-bg" x1="0" y1="0" x2="0.3" y2="1">
      <stop offset="0" stop-color="${a.stops[0]}"/>
      <stop offset="${a.mid}" stop-color="${a.stops[1]}"/>
      <stop offset="1" stop-color="${a.stops[2]}"/>
    </linearGradient>
  </defs>
  <rect width="1024" height="1024" fill="url(#p4-${name}-bg)"/>
  <g>
    ${fullRects(a.paper)}
  </g>
</svg>
`;

const layerSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024">
  <title>Pundoku — P4 foreground layer for Icon Composer</title>
  <desc>Production layer. Flat, opaque, full white, transparent background, no platform mask, no baked effects (app-icons.md › Visual effects). One group: nine cells. Ground gradient and the light/dark/tinted fills are defined in Icon Composer (materials in design/pd155-icons.mjs). Generated by design/pd155-icons.mjs.</desc>
  <g id="cells" fill="#FFFFFF">
    ${fullRects("#FFFFFF").replace(/ fill="#FFFFFF"/g, "")}
  </g>
</svg>
`;

const markSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024" role="img" aria-label="Pundoku mark, P4 Nine Cells">
  <title>Pundoku — знак P4 «Девять клеток»</title>
  <desc>Monochrome glyph in currentColor (full optics, for Mark.tsx above 60 px): nine rounded cells, the counter is an empty cell. Generated by design/pd155-icons.mjs.</desc>
  <g fill="currentColor">
    ${fullRects("currentColor").replace(/ fill="currentColor"/g, "")}
  </g>
</svg>
`;

const faviconSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16" shape-rendering="crispEdges" role="img" aria-label="Pundoku">
  <title>Pundoku — знак P4 «Девять клеток» — favicon (клетки)</title>
  <desc>The P4 mark with no ground plate on a 16-unit grid: nine 3x3 cells with 1-unit gaps, every edge on an integer, so at 24, 32, 48 and 64 px edges rasterize with no antialiasing. For 24 px and above; below that use p4-favicon-solid.svg (the same P without gaps). One colour, #5F6DF2 (4.24:1 on a white tab, 4.02:1 on a dark one); deliberately not wrapped in prefers-color-scheme (Safari ignores it inside an SVG favicon). The same cells are what Mark.tsx draws from 24 to 60 px. Generated by design/pd155-icons.mjs.</desc>
  <g fill="${INK_FAVICON}">
    ${smallRects()}
  </g>
</svg>
`;

const faviconSolidSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16" shape-rendering="crispEdges" role="img" aria-label="Pundoku">
  <title>Pundoku — знак P4 «Девять клеток» — favicon 16 px (сплошная)</title>
  <desc>The same P without gaps for 16 px, where a 1-px gap is noise: stem (3,1,3,14), top bar (3,1,11,3), bowl wall (11,1,3,9), bowl bottom (3,7,11,3) as one outline, counter 5x3 as a hole. No antialiased pixel. Colour #5F6DF2. Generated by design/pd155-icons.mjs.</desc>
  <path fill="${INK_FAVICON}" d="${SOLID_D}"/>
</svg>
`;

const FILES = {
  "p4-icon-light.svg": iconSvg("light", APPEAR.light),
  "p4-icon-dark.svg": iconSvg("dark", APPEAR.dark),
  "p4-icon-tinted.svg": iconSvg("tinted", APPEAR.tinted),
  "p4-layer-fg.svg": layerSvg,
  "p4-mark.svg": markSvg,
  "p4-favicon.svg": faviconSvg,
  "p4-favicon-solid.svg": faviconSolidSvg,
};
for (const [name, text] of Object.entries(FILES)) writeFileSync(join(ASSETS, name), text);
console.log(`wrote ${Object.keys(FILES).length} SVG -> design/pd155-assets/`);

// [файл, размер, исходник, прозрачный фон]
const TARGETS = [
  ["icon-192.png", 192, "p4-icon-light.svg", false],
  ["icon-512.png", 512, "p4-icon-light.svg", false],
  ["apple-touch-icon-180.png", 180, "p4-icon-light.svg", false],
  ["favicon-32.png", 32, "p4-favicon.svg", true],
  ["favicon-16.png", 16, "p4-favicon-solid.svg", true],
];

const browser = await chromium.launch();
try {
  for (const [name, size, src, alpha] of TARGETS) {
    const ctx = await browser.newContext({ viewport: { width: size, height: size }, deviceScaleFactor: 1 });
    const page = await ctx.newPage();
    // Грузим SVG как <img>: тот же растеризатор, что у favicon/apple-touch, без влияния CSS страницы.
    const uri = "data:image/svg+xml;base64," + Buffer.from(FILES[src]).toString("base64");
    await page.setContent(
      `<!doctype html><meta charset="utf-8"><style>html,body{margin:0;background:${alpha ? "transparent" : "#000"}}img{display:block;width:${size}px;height:${size}px}</style><img id="i" src="${uri}">`,
    );
    await page.waitForFunction(() => document.getElementById("i").complete && document.getElementById("i").naturalWidth > 0);
    const png = await page.screenshot({ omitBackground: alpha, type: "png", clip: { x: 0, y: 0, width: size, height: size } });
    writeFileSync(join(OUT, name), png);
    console.log(`wrote ${name} (${size}x${size}) <- ${src}`);
    await ctx.close();
  }
} finally {
  await browser.close();
}
copyFileSync(join(ASSETS, "p4-favicon.svg"), join(OUT, "icon.svg"));
console.log("wrote icon.svg <- p4-favicon.svg");
