import { pw, ctxFor, Session, BASE } from "./u.mjs";
import { readFileSync } from "node:fs";
const key = readFileSync("key.txt","utf8");
const b = await pw.webkit.launch();
const ctx = await ctxFor(b, { storageState: JSON.parse(readFileSync("state-a3.json", "utf8")) });
const page = await ctx.newPage(); const s = new Session(page, "V12");
await page.goto(BASE + "/#/year"); await page.waitForTimeout(1500);
s.log("before:", (await s.text()).slice(0, 120));
await page.goto(BASE + "/#/today"); await page.waitForTimeout(1500);
s.log("today before:", (await s.text()).slice(0, 150));
await page.goto(BASE + "/#/settings"); await page.waitForTimeout(1000);
await s.tap(page.getByTestId("key-have"), "have key");
await page.getByTestId("key-field").fill(key);
await s.tap(page.getByTestId("key-restore"), "restore"); await page.waitForTimeout(3000);
s.log("res:", (await s.text()).slice(0, 120));
await page.goto(BASE + "/#/year"); await page.waitForTimeout(1500);
s.log("year after:", (await s.text()).slice(0, 120));
await page.goto(BASE + "/#/today"); await page.waitForTimeout(1500);
s.log("today after:", (await s.text()).slice(0, 200));
await s.shot("S56-merge-today");
await b.close();
