import { pw, ctxFor, Session, BASE } from "./u.mjs";
import { readFileSync } from "node:fs";
const b = await pw.webkit.launch();
const ctx = await ctxFor(b, { storageState: JSON.parse(readFileSync("state-vet2.json", "utf8")) });
const page = await ctx.newPage(); const s = new Session(page, "V5");
page.on("pageerror", e => s.log("PAGEERROR", e.message));
await page.goto(BASE + "/#/year"); await page.waitForSelector(".year"); await page.waitForTimeout(700);
await s.tap(page.locator(".year-month").nth(8), "Sep"); await page.waitForTimeout(600);
await s.tap(page.locator('[role=dialog] button, .sheet button').filter({ hasText: /^29$/ }).first(), "Sep 29"); await page.waitForTimeout(600);
await s.shot("S36-solved-day-card-in-year");
await s.tap(page.getByRole("button", { name: /Watch your solve/ }), "Watch your solve"); await page.waitForTimeout(900);
await s.shot("S37-timelapse-contact-sheet");
s.log("T1:", (await s.text()).split("Your solve")[1]?.slice(0, 300));
await s.tap(page.getByRole("button", { name: /Play the replay/ }), "Play the replay"); 
await page.waitForTimeout(1200);
await s.shot("S38-timelapse-player-1s");
s.log("T2 buttons:", await page.evaluate(() => [...document.querySelectorAll("[role=dialog] button, .tl button, .sheet button")].map(b => (b.getAttribute("aria-label") || b.innerText || "").trim().replace(/\n/g," ")).join(" ; ")));
s.log("T2 text:", (await s.text()).split("Your solve")[1]?.slice(0, 300));
await page.waitForTimeout(6000);
await s.shot("S39-timelapse-player-7s");
s.log("T3 text:", (await s.text()).split("Your solve")[1]?.slice(0, 300));
await b.close();
